# agents/format_agent.py
# FormatAgent updated to respect the requested slide count more closely.

from .base_agent import BaseAgent
import math # Import math for ceiling function

class FormatAgent(BaseAgent):
    """
    Converts the chapter/topic structure into a slide plan,
    attempting to adhere to the requested number of content slides.
    """

    def run(self):
        self.log("Starting slide skeleton creation...")

        chapters = self.sm.get("chapters")
        requested_content_slides = self.sm.get("slide_count") or 10 # Get requested count

        if not chapters:
            self.log("ERROR: No chapters found in state. Aborting.")
            return

        initial_slides = []
        slide_counter = 1

        # --- Step 1: Generate ALL possible slides first ---
        initial_slides.append({
            "id": f"slide_{slide_counter}", "type": "main_title",
            "title": "Educational Presentation", # Generic title, could be improved
            "subtitle": "Auto-Generated by the Multi-Agent System"
        })
        slide_counter += 1

        content_slide_candidates = [] # Store potential content slides here
        quiz_slide_candidates = []    # Store potential quiz slides

        for ch_idx, ch in enumerate(chapters):
            initial_slides.append({
                "id": f"slide_{slide_counter}", "type": "chapter_title",
                "title": ch.get("title", f"Chapter {ch_idx+1}"),
                "subtitle": ch.get("description", "")
            })
            slide_counter += 1

            chapter_quiz_questions = []
            for topic in ch.get("topics", []):
                # Add topic content slides to a separate list for now
                content_slide_candidates.append({
                    "id": f"slide_{slide_counter}", "type": "content",
                    "title": topic.get("title", "Untitled Topic"),
                    "bullets": topic.get("key_points", []),
                    "image_hint": topic.get("image_hint"),
                    "diagram_dot_code": topic.get("diagram_dot_code"),
                    "chart_suggestion": topic.get("chart_suggestion"),
                    "chart_data": topic.get("chart_data"),
                    "speaker_notes": topic.get("speaker_notes") # Pass notes along
                })
                slide_counter += 1
                chapter_quiz_questions.extend(topic.get("quiz_questions", []))

            # Store potential quiz slide for this chapter
            if chapter_quiz_questions:
                 quiz_slide_candidates.append({
                    "id": f"slide_{slide_counter}", "type": "quiz",
                    "title": f"{ch.get('title', f'Chapter {ch_idx+1}')} Quiz",
                    "bullets": chapter_quiz_questions # Store raw questions/dicts
                 })
                 slide_counter += 1 # Increment even if not used, keeps IDs unique

        # --- Step 2: Select slides based on requested count ---
        final_slides = []
        # Add title slides (main + chapter titles)
        final_slides.extend([s for s in initial_slides if s['type'] in ['main_title', 'chapter_title']])

        # Add the requested number of content slides (or fewer if not enough generated)
        num_content_to_add = min(requested_content_slides, len(content_slide_candidates))
        final_slides.extend(content_slide_candidates[:num_content_to_add])
        self.log(f"Selected {num_content_to_add} content slides based on request for approx {requested_content_slides}.")

        # Add Quiz slides (maybe limit to 1 or 2, or add all generated ones?)
        # Let's add all generated quiz slides for now.
        final_slides.extend(quiz_slide_candidates)

        # Add final "Thank You" slide
        final_slides.append({
            "id": f"slide_{slide_counter}", "type": "thank_you",
            "title": "Thank You!", "subtitle": "Any Questions?"
        })

        # Re-assign sequential IDs to the final selection for neatness
        for idx, slide in enumerate(final_slides):
             slide['id'] = f"slide_{idx+1}"

        self.update_state("slides", final_slides)
        self.log(f"Final slide skeleton created with {len(final_slides)} slides total.")
        self.sm.save("shared_state_after_format.json")
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          # # agents/format_agent.py
# # FormatAgent → correctly reads that and produces a slide skeleton.

# from .base_agent import BaseAgent

# class FormatAgent(BaseAgent):
#     """
#     Converts chapters/topics into a slide skeleton (dummy version).
#     """

#     def run(self):
#         self.log("Starting dummy slide skeleton creation...")

#         chapters = self.sm.get("chapters")
#         if not chapters:
#             self.log("No chapters found! Aborting.")
#             return

#         slides = []

#         for ch in chapters:
#             # Title slide for chapter
#             slides.append({
#                 "id": f"{ch['id']}_title",
#                 "type": "title",
#                 "title": ch["title"],
#                 "content": ""
#             })

#             for topic in ch["topics"]:
#                 slides.append({
#                     "id": topic["id"],
#                     "type": "content",
#                     "title": topic["title"],
#                     "content": topic["summary"],
#                     "key_points": topic["key_points"]
#                 })

#             # Dummy summary slide
#             slides.append({
#                 "id": f"{ch['id']}_summary",
#                 "type": "summary",
#                 "title": f"{ch['title']} Summary",
#                 "content": "This chapter covered all topics above."
#             })

#         self.update_state("slides", slides)
#         self.log(f"Dummy slides created: {len(slides)}")
